// Nathan Shulkin
// Lujo Lifestyle script
//
// All code was written and/or generated by Nathan Shulkin
// for use in the LUJO website and is therefore
// intellectual property of Nathan Shulkin; whom has given
// permission for LUJO to use code in accordance with
// agreed upon terms. Any attempt to use this code without
// permission from the author is prohibited.
//

const app = document.getElementById('root');

// create containers for main, hand bags, boots, story
const mainContainer = document.createElement('div');
mainContainer.setAttribute('class', 'container');

const handbagContainer = document.createElement('div');
handbagContainer.setAttribute('class', 'container');

const bootContainer = document.createElement('div');
bootContainer.setAttribute('class', 'container');

const storyContainer = document.createElement('div');
storyContainer.setAttribute('class', 'container');

// hide the non main containers
handbagContainer.style.display = "none";
bootContainer.style.display = "none";
storyContainer.style.display = "none";


// main page
const createdBy = document.createElement('div');
createdBy.setAttribute('class', 'bottomCard');
const createdByText = document.createElement('p');
createdByText.textContent="Website Built by Nathan Shulkin";

createdBy.appendChild(createdByText);

// drop down button click
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function dropdownClick() {
  document.getElementById("myDropdown").classList.toggle("show");
  document.getElementById("myDropdown").animate({
                                                  opacity:'+=0.2',
                                                  height: '+=50px',
                                                  margin: '-=20px'
                                                });
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}

// button clicks
function logoClick()
{
  mainContainer.style.display="flex";
  handbagContainer.style.display = "none";
  bootContainer.style.display = "none";
  storyContainer.style.display = "none";
}

function instaClick()
{
  window.open('https://www.instagram.com/lujolifestylebrand');
}

function storyClick() {
  window.scrollTo(0, 2490);
}

function handbagClick() {
  window.scrollTo(0, 1720);
}

function bootsClick() {
  mainContainer.style.display = "none";
  handbagContainer.style.display = "none";
  storyContainer.style.display = "none";
  bootContainer.style.display = "flex";
  //bootContainer.style.visibility = "visible";
  //window.open("index.html", "_self");
}

function arrangeClick() {
  //parent.location='mailto:terry@lujolifestylebrand.com';
  window.open('mailto:terry@lujolifestylebrand.com', "_self");
}

// create menu
const ddown = document.createElement('div');
ddown.setAttribute('class', 'menuUp');

const rightMenu = document.createElement('div');
rightMenu.setAttribute('class', 'thinCard')

const logoCard = document.createElement('div');
logoCard.setAttribute('class', 'tinyLogoCard');
const menuLogo = document.createElement('img');
menuLogo.src = "photos/LUJO_white_FINAL-02.png";
menuLogo.addEventListener("click", logoClick);

logoCard.appendChild(menuLogo);
rightMenu.appendChild(logoCard);

const leftMenu = document.createElement('div');
leftMenu.setAttribute('class', 'thinCenterCard');

const storyCard = document.createElement('div');
storyCard.setAttribute('class', 'tinyCard');
const storyTxt = document.createElement('div')
storyTxt.textContent="Our Story";

storyCard.addEventListener("click", storyClick);

storyCard.appendChild(storyTxt);
leftMenu.appendChild(storyCard);



// create clickable menu for webpage, add it to dropdown 
const menuDDown = document.createElement('div');
menuDDown.setAttribute('id', 'myDropdown');
menuDDown.setAttribute('class', 'dropdown-content');


const menuBoots = document.createElement('div');
menuBoots.setAttribute('class', 'menuCard');
menuBoots.textContent="Boots";
menuBoots.style.height="160%";

menuBoots.addEventListener("click", bootsClick);

const menuBag = document.createElement('div');
menuBag.setAttribute('class', 'menuCard');
menuBag.textContent="Hand Bags";
menuBag.style.height="160%";

menuBag.addEventListener("click", handbagClick);

//add menu
menuDDown.appendChild(menuBoots);
menuDDown.appendChild(menuBag);


// dropdown
const ourProdCard = document.createElement('div');
ourProdCard.setAttribute('class', 'dropbtn');
ourProdCard.textContent="Our Products";
ourProdCard.addEventListener("click", dropdownClick);


ourProdCard.appendChild(menuDDown);
leftMenu.appendChild(ourProdCard);



const contactUsCard = document.createElement('div');
contactUsCard.setAttribute('class', 'tinyCard');
const contactUsTxt = document.createElement('div');
contactUsTxt.textContent = "Contact Us";

contactUsCard.addEventListener("click", arrangeClick);

contactUsCard.appendChild(contactUsTxt);
leftMenu.appendChild(contactUsCard);

const followCard = document.createElement('div');
followCard.setAttribute('class', 'tinyCard');
const followTxt = document.createElement('div');
followTxt.textContent="Follow Us";
const instaImgCard = document.createElement('div');
instaImgCard.setAttribute('class', 'superTinyCard');
const instaImg = document.createElement('img');
instaImg.src = "photos/instagramLogo.png"
instaImgCard.appendChild(instaImg);

followCard.addEventListener("click", instaClick);
followCard.appendChild(instaImgCard);

leftMenu.appendChild(followCard);
rightMenu.appendChild(leftMenu);

ddown.appendChild(rightMenu);


// blank space
const p0 = document.createElement('p');
p0.textContent="\n\n\n\n\n";



//main container

// first image
const fiberCard = document.createElement('div');
fiberCard.setAttribute('class', 'entireCard');

const fiber = document.createElement('img');
fiber.src = 'photos/homeImage.png';

fiberCard.appendChild(fiber);

// main part
const bootsBagContainter = document.createElement('div');
bootsBagContainter.setAttribute('class', 'container');

// boots
const bootsCard = document.createElement('div');
bootsCard.setAttribute('class', 'card');

const bootsPic = document.createElement('img');
bootsPic.src = 'photos/bootsButtonFinal.png';

bootsCard.appendChild(bootsPic);

// hand bags
const bagCard = document.createElement('div');
bagCard.setAttribute('class', 'card');

const bagPic = document.createElement('img');
bagPic.src = 'photos/handBagButtonFinal.png';

bagCard.appendChild(bagPic);


// our story
const ourStoryCard = document.createElement('div');
ourStoryCard.setAttribute('class', 'card');

const storyPic = document.createElement('img');
storyPic.src = 'photos/ourStoryButton.png';

ourStoryCard.appendChild(storyPic);

bootsBagContainter.appendChild(bootsCard);
bootsBagContainter.appendChild(bagCard);
bootsBagContainter.appendChild(ourStoryCard);




// add elements to main container
mainContainer.appendChild(fiberCard);
mainContainer.appendChild(p0);
mainContainer.appendChild(bootsBagContainter);
mainContainer.appendChild(createdBy);

// boot container
// boots
const bibidyBootsCard = document.createElement('div');
bibidyBootsCard.setAttribute('class', 'card');

const bibidyBootsPic = document.createElement('img');
bibidyBootsPic.src = 'paulinaLamb.jpg';

bibidyBootsCard.appendChild(bibidyBootsPic);

bootContainer.appendChild(bibidyBootsCard);


// add containers to page
app.appendChild(ddown)
app.appendChild(mainContainer);
app.appendChild(bootContainer);
