// Nathan Shulkin
// Lujo Lifestyle script
//
// All code was written and/or generated by Nathan Shulkin
// for use in the LUJO website and is therefore
// intellectual property of Nathan Shulkin; whom has given
// permission for LUJO to use code in accordance with
// agreed upon terms. Any attempt to use this code without
// permission from the author is prohibited.
//

const app = document.getElementById('root');

// create containers for main, hand bags, boots, story
const mainContainer = document.createElement('div');
mainContainer.setAttribute('class', 'container');

const handbagContainer = document.createElement('div');
handbagContainer.setAttribute('class', 'container');

const bootContainer = document.createElement('div');
bootContainer.setAttribute('class', 'container');

const storyContainer = document.createElement('div');
storyContainer.setAttribute('class', 'container');

const socialEntContainer = document.createElement('div');
socialEntContainer.setAttribute('class', 'container');

// hide the non main containers
handbagContainer.style.display = "none";
bootContainer.style.display = "none";
storyContainer.style.display = "none";


// main page
const createdBy = document.createElement('div');
createdBy.setAttribute('class', 'bottomCard');
const createdByText = document.createElement('p');
createdByText.style.textAlign="center";
createdByText.textContent="Website Built by Nathan Shulkin";

createdBy.appendChild(createdByText);

// drop down button click
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function dropdownClick() {
  document.getElementById("myDropdown").classList.toggle("show");
  document.getElementById("myDropdown").animate({
                                                  opacity:'+=0.2',
                                                  height: '+=50px',
                                                  margin: '-=20px'
                                                });
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}

// button clicks
function logoClick()
{
  window.scrollTo(0, 0);
  mainContainer.style.display="flex";
  handbagContainer.style.display = "none";
  bootContainer.style.display = "none";
  storyContainer.style.display = "none";
  socialEntContainer.style.display = "none";
}

function instaClick()
{
  window.open('https://www.instagram.com/lujolifestylebrand');
}

function storyClick() {
  window.scrollTo(0, 0);
  mainContainer.style.display="none";
  handbagContainer.style.display = "none";
  bootContainer.style.display = "none";
  storyContainer.style.display = "flex";
  socialEntContainer.style.display = "none";
}

function handbagClick() {
  window.scrollTo(0, 0);
  mainContainer.style.display="none";
  handbagContainer.style.display = "flex";
  bootContainer.style.display = "none";
  storyContainer.style.display = "none";
  socialEntContainer.style.display = "none";
}

function bootsClick() {
  window.scrollTo(0, 0);
  mainContainer.style.display="none";
  handbagContainer.style.display = "none";
  bootContainer.style.display = "flex";
  storyContainer.style.display = "none";
  socialEntContainer.style.display = "none";
}

function socialEntClick() {
  window.scrollTo(0, 0);
  mainContainer.style.display="none";
  handbagContainer.style.display = "none";
  bootContainer.style.display = "none";
  storyContainer.style.display = "none";
  socialEntContainer.style.display = "flex";
}

function arrangeClick() {
  //parent.location='mailto:terry@lujolifestylebrand.com';
  window.open('mailto:terry@lujolifestylebrand.com', "_self");
}

// create menu
const ddown = document.createElement('div');
ddown.setAttribute('class', 'menuUp');

const rightMenu = document.createElement('div');
rightMenu.setAttribute('class', 'thinCard')

const logoCard = document.createElement('div');
logoCard.setAttribute('class', 'tinyLogoCard');
const menuLogo = document.createElement('img');
menuLogo.src = "photos/LUJO_NEW_white_logo_2020.png";
menuLogo.addEventListener("click", logoClick);

logoCard.appendChild(menuLogo);
rightMenu.appendChild(logoCard);

const leftMenu = document.createElement('div');
leftMenu.setAttribute('class', 'thinCenterCard');


const socialEntMenu = document.createElement('div');
socialEntMenu.setAttribute('class', 'tinyCard');
socialEntMenu.style.width="22%";
const entText = document.createElement('div');
entText.textContent = "Social Enterprise";

socialEntMenu.addEventListener("click", socialEntClick);

socialEntMenu.appendChild(entText);
leftMenu.appendChild(socialEntMenu);


const storyCard = document.createElement('div');
storyCard.setAttribute('class', 'tinyCard');
const storyTxt = document.createElement('div')
storyTxt.textContent="Our Story";

storyCard.addEventListener("click", storyClick);

storyCard.appendChild(storyTxt);
leftMenu.appendChild(storyCard);



// create clickable menu for webpage, add it to dropdown 
const menuDDown = document.createElement('div');
menuDDown.setAttribute('id', 'myDropdown');
menuDDown.setAttribute('class', 'dropdown-content');


const menuBoots = document.createElement('div');
menuBoots.setAttribute('class', 'menuCard');
menuBoots.textContent="Boots";
menuBoots.style.height="160%";

menuBoots.addEventListener("click", bootsClick);

const menuBag = document.createElement('div');
menuBag.setAttribute('class', 'menuCard');
menuBag.textContent="Hand Bags";
menuBag.style.height="160%";

menuBag.addEventListener("click", handbagClick);

//add menu
menuDDown.appendChild(menuBoots);
menuDDown.appendChild(menuBag);


// dropdown
const ourProdCard = document.createElement('div');
ourProdCard.setAttribute('class', 'dropbtn');
ourProdCard.textContent="Our Products";
ourProdCard.addEventListener("click", dropdownClick);


ourProdCard.appendChild(menuDDown);
leftMenu.appendChild(ourProdCard);


const contactUsCard = document.createElement('div');
contactUsCard.setAttribute('class', 'tinyCard');
const contactUsTxt = document.createElement('div');
contactUsTxt.textContent = "Contact Us";

contactUsCard.addEventListener("click", arrangeClick);

contactUsCard.appendChild(contactUsTxt);
leftMenu.appendChild(contactUsCard);

const followCard = document.createElement('div');
followCard.setAttribute('class', 'tinyCard');
const followTxt = document.createElement('div');
followTxt.textContent="Follow Us";
const instaImgCard = document.createElement('div');
instaImgCard.setAttribute('class', 'superTinyCard');
const instaImg = document.createElement('img');
instaImg.src = "photos/instagramLogo.png"
instaImgCard.appendChild(instaImg);

followCard.addEventListener("click", instaClick);
followCard.appendChild(instaImgCard);

leftMenu.appendChild(followCard);
rightMenu.appendChild(leftMenu);

ddown.appendChild(rightMenu);


// blank space
const p0 = document.createElement('p');
p0.textContent="\n\n\n\n\n";



//main container

// first image
const fiberCard = document.createElement('div');
fiberCard.setAttribute('class', 'entireCard');

const fiber = document.createElement('img');
fiber.src = 'photos/homeImage.png';

fiberCard.appendChild(fiber);

// main part
const bootsBagContainter = document.createElement('div');
bootsBagContainter.setAttribute('class', 'container');

// boots
const bootsCard = document.createElement('div');
bootsCard.setAttribute('class', 'card');

const bootsPic = document.createElement('img');
bootsPic.src = 'photos/bootsButtonFinal.png';

bootsCard.addEventListener("click", bootsClick)

bootsCard.appendChild(bootsPic);

// hand bags
const bagCard = document.createElement('div');
bagCard.setAttribute('class', 'card');

const bagPic = document.createElement('img');
bagPic.src = 'photos/handBagButtonFinal.png';

bagCard.addEventListener("click", handbagClick)


bagCard.appendChild(bagPic);


// our story
const ourStoryCard = document.createElement('div');
ourStoryCard.setAttribute('class', 'card');

const storyPic = document.createElement('img');
storyPic.src = 'photos/ourStoryButton.png';

ourStoryCard.addEventListener("click", storyClick)

ourStoryCard.appendChild(storyPic);

// social enterprise
const socialEntCard = document.createElement('div');
socialEntCard.setAttribute('class', 'card');

const entPic = document.createElement('img');
entPic.src = 'photos/socialEnt.png';

socialEntCard.addEventListener("click", socialEntClick);

socialEntCard.appendChild(entPic);

bootsBagContainter.appendChild(bootsCard);
bootsBagContainter.appendChild(bagCard);
bootsBagContainter.appendChild(ourStoryCard);
bootsBagContainter.appendChild(socialEntCard);


// add elements to main container
mainContainer.appendChild(fiberCard);
mainContainer.appendChild(p0);
mainContainer.appendChild(bootsBagContainter);
mainContainer.appendChild(createdBy);



// boot container
// boots
const headBootCont = document.createElement('div');
headBootCont.setAttribute('class', 'container');
headBootCont.style.backgroundColor="#000000";

const bibidyBootsCard = document.createElement('div');
bibidyBootsCard.setAttribute('class', 'thirdCard');

const bibidyBootsPic = document.createElement('img');
bibidyBootsPic.src = 'photos/blackBckBoots.jpg';

bibidyBootsCard.appendChild(bibidyBootsPic);

const bibidyBootsText = document.createElement('div');
bibidyBootsText.setAttribute('class', 'twoThirdCard');

const headBootTxt = document.createElement('p');
headBootTxt.textContent = "Enhance your boot collection with a pair of LUJO boots.";

const headBootTxt1 = document.createElement('p');
headBootTxt1.textContent = "LUJO boots are handcrafted using textiles created by a collaboration" + 
" of artisas in Patagonia, Chile. LUJO artisans create one of a kind textiles using both" + 
"scarce and extremely fine fiber.";

const headBootTxt2 = document.createElement('p');
headBootTxt2.textContent = "Chilean artisans create LUJO textiles in small batches using a" + 
" time honored process. LUJO textiles - one of a kind design.";

const headBootTxt3 = document.createElement('p');
headBootTxt3.textContent = "LUJO partners with Back at the Ranch boots... to design versatile" + 
" boots that fit your personal style.";

bibidyBootsText.appendChild(headBootTxt);
bibidyBootsText.appendChild(headBootTxt1);
bibidyBootsText.appendChild(headBootTxt2);
bibidyBootsText.appendChild(headBootTxt3);


headBootCont.appendChild(bibidyBootsCard);
headBootCont.appendChild(bibidyBootsText);

// container for boots
const bootPageBootsContainer = document.createElement('div');
bootPageBootsContainer.setAttribute('class', 'container');
bootPageBootsContainer.style.backgroundColor="#FCFCFC";


// first line of rainbow python boots
const rainPython = document.createElement('div');
rainPython.setAttribute('class', 'quarterCard');
const rainPythonImg = document.createElement('img');
rainPythonImg.src = 'photos/rainbowPython.JPG';
rainPython.appendChild(rainPythonImg);

const redPython = document.createElement('div');
redPython.setAttribute('class', 'quarterCard');
const redPythonImg = document.createElement('img');
redPythonImg.src = 'photos/rainbowPython2.JPG';
redPython.appendChild(redPythonImg);

const greenPython = document.createElement('div');
greenPython.setAttribute('class', 'quarterCard');
const greenPythonImg = document.createElement('img');
greenPythonImg.src = 'photos/rainbowPython3.JPG';
greenPython.appendChild(greenPythonImg);

const bluePython = document.createElement('div');
bluePython.setAttribute('class', 'quarterCardText');
const bluePythonText = document.createElement('p');
bluePythonText.style.color="#000000";
bluePythonText.textContent="Python Skin on Foot";
bluePython.appendChild(bluePythonText);

const bootText = document.createElement('p');
bootText.style.color="#000000";
bootText.textContent="14 \" Height";
bluePython.appendChild(bootText);

const bootText1 = document.createElement('p');
bootText1.style.color="#000000";
bootText1.textContent="100% Merino Wool Upper";
bluePython.appendChild(bootText1);

const bootText2 = document.createElement('p');
bootText2.style.color="#000000";
bootText2.textContent="5/8 \" Box Toe";
bluePython.appendChild(bootText2);

const bootText3 = document.createElement('p');
bootText3.style.color="#000000";
bootText3.textContent="2 \" Heel";
bluePython.appendChild(bootText3);

bootPageBootsContainer.appendChild(rainPython);
bootPageBootsContainer.appendChild(redPython);
bootPageBootsContainer.appendChild(greenPython);
bootPageBootsContainer.appendChild(bluePython);



// second line of pink python boots

const pinkPython = document.createElement('div');
pinkPython.setAttribute('class', 'quarterCard');
const pinkPythonImg = document.createElement('img');
pinkPythonImg.src = 'photos/pinkPython.JPG';
pinkPython.appendChild(pinkPythonImg);

const pinkPython1 = document.createElement('div');
pinkPython1.setAttribute('class', 'quarterCard');
const pinkPython1Img = document.createElement('img');
pinkPython1Img.src = 'photos/pinkPython2.JPG';
pinkPython1.appendChild(pinkPython1Img);

const pinkPython2 = document.createElement('div');
pinkPython2.setAttribute('class', 'quarterCard');
const pinkPython2Img = document.createElement('img');
pinkPython2Img.src = 'photos/pinkPython3.JPG';
pinkPython2.appendChild(pinkPython2Img);

const bluePython1 = document.createElement('div');
bluePython1.setAttribute('class', 'quarterCardText');
const bluePython1Text = document.createElement('p');
bluePython1Text.style.color="#000000";
bluePython1Text.textContent="Python Skin on Foot";
bluePython1.appendChild(bluePython1Text);

const bootText10 = document.createElement('p');
bootText10.style.color="#000000";
bootText10.textContent="14 \" Height";
bluePython1.appendChild(bootText10);

const bootText11 = document.createElement('p');
bootText11.style.color="#000000";
bootText11.textContent="100% Merino Wool Upper";
bluePython1.appendChild(bootText11);

const bootText12 = document.createElement('p');
bootText12.style.color="#000000";
bootText12.textContent="5/8 \" Box Toe";
bluePython1.appendChild(bootText12);

const bootText13 = document.createElement('p');
bootText13.style.color="#000000";
bootText13.textContent="2 \" Heel";
bluePython1.appendChild(bootText13);


bootPageBootsContainer.appendChild(pinkPython);
bootPageBootsContainer.appendChild(pinkPython1);
bootPageBootsContainer.appendChild(pinkPython2);
bootPageBootsContainer.appendChild(bluePython1);




// third line of peacock boots

const peacock = document.createElement('div');
peacock.setAttribute('class', 'quarterCard');
const peacockImg = document.createElement('img');
peacockImg.src = 'photos/peacockUpdate.png';
peacock.appendChild(peacockImg);

const peacock1 = document.createElement('div');
peacock1.setAttribute('class', 'quarterCard');
const peacock1Img = document.createElement('img');
peacock1Img.src = 'photos/peacock2.JPG';
peacock1.appendChild(peacock1Img);

const peacock2 = document.createElement('div');
peacock2.setAttribute('class', 'quarterCard');
const peacock2Img = document.createElement('img');
peacock2Img.src = 'photos/peacock3.JPG';
peacock2.appendChild(peacock2Img);

const bluePython2 = document.createElement('div');
bluePython2.setAttribute('class', 'quarterCardText');
const bluePython2Text = document.createElement('p');
bluePython2Text.style.color="#000000";
bluePython2Text.textContent="Peacock Skin on Foot";
bluePython2.appendChild(bluePython2Text);

const bootText20 = document.createElement('p');
bootText20.style.color="#000000";
bootText20.textContent="14 \" Height";
bluePython2.appendChild(bootText20);

const bootText21 = document.createElement('p');
bootText21.style.color="#000000";
bootText21.textContent="100% Merino Wool Upper";
bluePython2.appendChild(bootText21);

const bootText22 = document.createElement('p');
bootText22.style.color="#000000";
bootText22.textContent="5/8 \" Box Toe";
bluePython2.appendChild(bootText22);

const bootText23 = document.createElement('p');
bootText23.style.color="#000000";
bootText23.textContent="2 \" Heel";
bluePython2.appendChild(bootText23);


bootPageBootsContainer.appendChild(peacock);
bootPageBootsContainer.appendChild(peacock1);
bootPageBootsContainer.appendChild(peacock2);
bootPageBootsContainer.appendChild(bluePython2);



// fourth line of ostrich boots
/*
const ostrich = document.createElement('div');
ostrich.setAttribute('class', 'quarterCard');
const ostrichImg = document.createElement('img');
ostrichImg.src = 'photos/ostrich.jpg';
ostrich.appendChild(ostrichImg);

const ostrich1 = document.createElement('div');
ostrich1.setAttribute('class', 'quarterCard');
const ostrich1Img = document.createElement('img');
ostrich1Img.src = 'photos/ostrich1.jpg';
ostrich1.appendChild(ostrich1Img);

const ostrich2 = document.createElement('div');
ostrich2.setAttribute('class', 'quarterCard');
const ostrich2Img = document.createElement('img');
ostrich2Img.src = 'photos/ostrich2.jpg';
ostrich2.appendChild(ostrich2Img);

const bluePython3 = document.createElement('div');
bluePython3.setAttribute('class', 'quarterCard');
const bluePython3Text = document.createElement('p');
bluePython3Text.style.color="#000000";
bluePython3Text.textContent="Ostrich Skin on Foot";
bluePython3.appendChild(bluePython3Text);

const bootText30 = document.createElement('p');
bootText30.style.color="#000000";
bootText30.textContent="14 \" Height";
bluePython3.appendChild(bootText30);

const bootText31 = document.createElement('p');
bootText31.style.color="#000000";
bootText31.textContent="100% Merino Wool Upper";
bluePython3.appendChild(bootText31);

const bootText32 = document.createElement('p');
bootText32.style.color="#000000";
bootText32.textContent="5/8 \" Box Toe";
bluePython3.appendChild(bootText32);

const bootText33 = document.createElement('p');
bootText33.style.color="#000000";
bootText33.textContent="2 \" Heel";
bluePython3.appendChild(bootText33);


bootPageBootsContainer.appendChild(ostrich);
bootPageBootsContainer.appendChild(ostrich1);
bootPageBootsContainer.appendChild(ostrich2);
bootPageBootsContainer.appendChild(bluePython3);
*/


// fifth line of kiana boots

const kiana = document.createElement('div');
kiana.setAttribute('class', 'quarterCard');
const kianaImg = document.createElement('img');
kianaImg.src = 'photos/kiana.png';
kiana.appendChild(kianaImg);

const kiana1 = document.createElement('div');
kiana1.setAttribute('class', 'quarterCard');
const kiana1Img = document.createElement('img');
kiana1Img.src = 'photos/kiana1.png';
kiana1.appendChild(kiana1Img);

const kiana2 = document.createElement('div');
kiana2.setAttribute('class', 'quarterCard');
const kiana2Img = document.createElement('img');
kiana2Img.src = 'photos/kiana2.png';
kiana2.appendChild(kiana2Img);

const bluePython4 = document.createElement('div');
bluePython4.setAttribute('class', 'quarterCardText');
const bluePython4Text = document.createElement('p');
bluePython4Text.style.color="#000000";
bluePython4Text.textContent="Ostrich Skin on Foot";
bluePython4.appendChild(bluePython4Text);

const bootText40 = document.createElement('p');
bootText40.style.color="#000000";
bootText40.textContent="?? \" Height";
bluePython4.appendChild(bootText40);

const bootText41 = document.createElement('p');
bootText41.style.color="#000000";
bootText41.textContent="100% Merino Wool Upper";
bluePython4.appendChild(bootText41);

const bootText42 = document.createElement('p');
bootText42.style.color="#000000";
bootText42.textContent="5/8 \" Box Toe";
bluePython4.appendChild(bootText42);

const bootText43 = document.createElement('p');
bootText43.style.color="#000000";
bootText43.textContent="2 \" Heel";
bluePython4.appendChild(bootText43);


bootPageBootsContainer.appendChild(kiana);
bootPageBootsContainer.appendChild(kiana1);
bootPageBootsContainer.appendChild(kiana2);
bootPageBootsContainer.appendChild(bluePython4);



// sixth line of laura boots

const laura = document.createElement('div');
laura.setAttribute('class', 'quarterCard');
const lauraImg = document.createElement('img');
lauraImg.src = 'photos/laura0.png';
laura.appendChild(lauraImg);

const laura1 = document.createElement('div');
laura1.setAttribute('class', 'quarterCard');
const laura1Img = document.createElement('img');
laura1Img.src = 'photos/laura1.png';
laura1.appendChild(laura1Img);

const laura2 = document.createElement('div');
laura2.setAttribute('class', 'quarterCard');
const laura2Img = document.createElement('img');
laura2Img.src = 'photos/laura2.png';
laura2.appendChild(laura2Img);

const bluePython5 = document.createElement('div');
bluePython5.setAttribute('class', 'quarterCardText');
const bluePython5Text = document.createElement('p');
bluePython5Text.textContent="Ostrich Skin on Foot";
bluePython5Text.style.color="#000000";
bluePython5.appendChild(bluePython5Text);

const bootText50 = document.createElement('p');
bootText50.style.color="#000000";
bootText50.textContent="?? \" Height";
bluePython4.appendChild(bootText50);

const bootText51 = document.createElement('p');
bootText51.style.color="#000000";
bootText51.textContent="100% Merino Wool Upper";
bluePython5.appendChild(bootText41);

const bootText52 = document.createElement('p');
bootText52.style.color="#000000";
bootText52.textContent="5/8 \" Box Toe";
bluePython5.appendChild(bootText52);

const bootText53 = document.createElement('p');
bootText53.style.color="#000000";
bootText53.textContent="2 \" Heel";
bluePython5.appendChild(bootText53);


bootPageBootsContainer.appendChild(laura);
bootPageBootsContainer.appendChild(laura1);
bootPageBootsContainer.appendChild(laura2);
bootPageBootsContainer.appendChild(bluePython5);


bootContainer.appendChild(headBootCont);
bootContainer.appendChild(bootPageBootsContainer);




// hand bag page
// hand bag container
// boots
const handBagCont = document.createElement('div');
handBagCont.setAttribute('class', 'container');
handBagCont.style.backgroundColor="#000000";

const bibidyBagsCard = document.createElement('div');
bibidyBagsCard.setAttribute('class', 'thirdCard');

const bibidyBagsPic = document.createElement('img');
bibidyBagsPic.src = 'photos/blueCircleBag.png';

bibidyBagsCard.appendChild(bibidyBagsPic);

const bibidyBagsText = document.createElement('div');
bibidyBagsText.setAttribute('class', 'twoThirdCard');

const headBagTxt = document.createElement('p');
headBagTxt.textContent = "Still in progress...";

bibidyBagsText.appendChild(headBagTxt);


handBagCont.appendChild(bibidyBagsCard);
handBagCont.appendChild(bibidyBagsText);

handbagContainer.appendChild(handBagCont);



// add containers to page
app.appendChild(ddown)
app.appendChild(mainContainer);
app.appendChild(bootContainer);
app.appendChild(handbagContainer);
